// Code generated from clio master 914dab286 [Verb] attributes. DO NOT EDIT.

package main

// knowledgeClioVerbs maps every clio CLI verb to its aliases; docs://help/command/{name} resolves a name
// or alias to the verb whose help/en/<verb>.txt clio serves.
var knowledgeClioVerbs = map[string][]string{
	"CustomizeDataProtection":             {"cdp"},
	"activate-pkg":                        {"apkg", "activate-package", "enable-package"},
	"add-custom-logging":                  {},
	"add-data-binding-row":                {},
	"add-item":                            {"create"},
	"add-knowledge-source":                {},
	"add-package":                         {"ap"},
	"add-package-dependency":              {"add-pkg-dependency", "add-pkg-dep"},
	"add-schema":                          {},
	"add-user-task":                       {},
	"alm-deploy":                          {"deploy"},
	"apply-manifest":                      {"applym", "apply-environment-manifest"},
	"assert":                              {},
	"auth-status":                         {"whoami"},
	"autoupdate":                          {},
	"build-docker-image":                  {},
	"build-theme":                         {},
	"build-workspace":                     {"build", "compile", "compile-all", "rebuild"},
	"call-service":                        {"cs"},
	"cfg-worspace":                        {"cfgw"},
	"check-auth-code-flow":                {"auth-code-flow"},
	"check-nuget-update":                  {"check"},
	"check-windows-features":              {"checkw", "checks", "checkf", "cf"},
	"clear-browser-session":               {"clear-session"},
	"clear-local-env":                     {"clear-env"},
	"clear-redis-db":                      {"flushdb"},
	"clear-themes-cache":                  {"flush-themes"},
	"clone-env":                           {"clone", "clone-environment"},
	"compare-web-farm-node":               {"check-web-farm-node", "check-farm", "farm-check", "cwf"},
	"compile-configuration":               {"cc", "compile-remote"},
	"compile-package":                     {"comp-pkg"},
	"component-registry-refresh":          {"component-registry"},
	"compressApp":                         {"comp-app"},
	"config":                              {},
	"convert":                             {},
	"create-app":                          {},
	"create-app-section":                  {},
	"create-client-unit-schema":           {"client-unit-schema-create"},
	"create-data-binding":                 {},
	"create-data-binding-db":              {},
	"create-entity-schema":                {},
	"create-k8-files":                     {"ck8f"},
	"create-lookup":                       {},
	"create-oauth-technical-user":         {},
	"create-package":                      {},
	"create-page":                         {"page-create"},
	"create-related-page-addon":           {"related-page-addon", "set-related-pages"},
	"create-schema":                       {"schema-create"},
	"create-server-to-server-oauth-app":   {},
	"create-sql-schema":                   {"sql-schema-create"},
	"create-theme":                        {},
	"create-user-task-page":               {},
	"create-workspace":                    {"createw"},
	"dataservice":                         {"ds"},
	"deactivate-pkg":                      {"dpkg", "deactivate-package", "disable-package"},
	"delete-app-section":                  {},
	"delete-infrastructure":               {"di-delete", "remove-infrastructure"},
	"delete-knowledge":                    {},
	"delete-pkg-remote":                   {"delete"},
	"delete-schema":                       {},
	"delete-theme":                        {},
	"delete-toolkit":                      {"delete-skill"},
	"deploy-application":                  {"deploy-app"},
	"deploy-creatio":                      {"dc", "ic", "install-creatio"},
	"deploy-identity":                     {},
	"deploy-infrastructure":               {"di"},
	"disable-knowledge-source":            {},
	"distribute-license":                  {"grant-license"},
	"download-application":                {"dapp", "download-app"},
	"download-configuration":              {"dconf"},
	"download-sys-setting-file":           {},
	"enable-knowledge-source":             {},
	"enroll-sequence-participants":        {},
	"env-ui":                              {"gui", "far"},
	"execute-assembly-code":               {"exec"},
	"execute-dataservice-batch":           {},
	"execute-sql-script":                  {"sql"},
	"experimental":                        {"exp"},
	"export-component-registry":           {"export-registry"},
	"export-schema":                       {"schema-export"},
	"externalLink":                        {"link"},
	"extract-pkg-zip":                     {"extract", "unzip"},
	"find-app":                            {},
	"find-entity-schema":                  {},
	"generate-pkg-zip":                    {"comp-pkg", "compress"},
	"generate-process-model":              {"gpm"},
	"generate-source-code":                {"gsc"},
	"get-app-hash":                        {},
	"get-app-info":                        {},
	"get-browser-session":                 {"get-session"},
	"get-build-info":                      {"buildinfo", "bi"},
	"get-classic-list-columns":            {},
	"get-classic-page-sources":            {"classic-page-sources", "get-classic-migration-bundle", "classic-migration-bundle"},
	"get-client-unit-schema":              {"client-unit-schema-get"},
	"get-component-info":                  {"component-info"},
	"get-entity-schema-column-properties": {},
	"get-entity-schema-properties":        {},
	"get-identity-assertion":              {"identity-assertion"},
	"get-identity-public-jwk":             {"identity-public-jwk"},
	"get-identity-service-config":         {},
	"get-info":                            {"describe", "describe-creatio", "instance-info"},
	"get-page":                            {"page-get"},
	"get-page-hierarchy":                  {"page-hierarchy-get"},
	"get-pkg-version":                     {"gpv"},
	"get-process-page-facts":              {"page-facts"},
	"get-process-signature":               {"gps"},
	"get-record-rights":                   {},
	"get-related-page-addon":              {"related-page-addon-get", "get-related-pages"},
	"get-schema":                          {"schema-get"},
	"get-sequence-context":                {},
	"get-sql-schema":                      {"sql-schema-get"},
	"get-target-package":                  {},
	"get-theme":                           {},
	"get-user-culture":                    {"profile-language"},
	"get-webservice-url":                  {"gwu"},
	"git-sync":                            {"sync"},
	"healthcheck":                         {"hc"},
	"hosts":                               {"list-hosts"},
	"idp-bind":                            {},
	"idp-delete":                          {},
	"idp-list":                            {},
	"idp-services":                        {},
	"idp-set-default":                     {},
	"idp-set-secret":                      {},
	"idp-unbind":                          {},
	"idp-upsert":                          {},
	"import-schema":                       {"schema-import"},
	"info":                                {"ver", "get-version", "i"},
	"info-knowledge":                      {},
	"install-application":                 {"push-app", "install-app"},
	"install-dashboards-migrator":         {"update-dashboards-migrator", "installdashboardsmigrator", "idm", "udm"},
	"install-dbhub":                       {},
	"install-gate":                        {"gate", "update-gate", "installgate"},
	"install-knowledge":                   {},
	"install-nuget-pkg":                   {"installng"},
	"install-process-builder":             {"update-process-builder", "installprocessbuilder"},
	"install-sql-schema":                  {"sql-schema-install", "execute-sql-schema"},
	"install-toolkit":                     {"install-skills"},
	"last-compilation-log":                {"lcl"},
	"link-core-src":                       {"lcs"},
	"link-from-repository":                {"l4r", "link4repo"},
	"link-package-store":                  {"lps"},
	"link-to-repository":                  {"l2r", "link2repo"},
	"link-workspace-with-tide-repository": {"linkw"},
	"list-app-sections":                   {},
	"list-apps":                           {"get-app-list", "lia", "apps", "app-list", "apps-list", "list - installed - applications"},
	"list-entity-client-schemas":          {"migration-unit-resolve"},
	"list-environments":                   {"show-web-app-list", "env", "envs", "show-web-app"},
	"list-knowledge-examples":             {},
	"list-knowledge-sources":              {},
	"list-packages":                       {"get-pkg-list", "packages"},
	"list-page-templates":                 {"page-templates", "page-templates-list"},
	"list-pages":                          {"page-list"},
	"list-printables":                     {},
	"list-themes":                         {"get-themes"},
	"listen":                              {},
	"localize-page":                       {},
	"lock-package":                        {"lp"},
	"login":                               {"signin"},
	"logout":                              {"signout"},
	"manage-access":                       {},
	"manage-license":                      {},
	"manage-role":                         {},
	"manage-user":                         {},
	"manage-windows-features":             {"mwf", "mng-win-features"},
	"mcp-http":                            {},
	"mcp-server":                          {"mcp"},
	"merge-creatio-artifact":              {},
	"merge-workspaces":                    {"mergew"},
	"mock-data":                           {"data-mock"},
	"modify-entity-schema-column":         {},
	"modify-user-task-parameters":         {},
	"new-integration-test-project":        {"integration-test"},
	"new-pkg":                             {"init"},
	"new-test-project":                    {"unit-test", "create-test-project"},
	"new-ui-project":                      {"ui", "create-ui-project", "new-ui", "createup", "uiproject"},
	"open-k8-files":                       {"cfg-k8f", "cfg-k8s", "cfg-k8"},
	"open-settings":                       {"conf", "configuration", "settings", "os"},
	"open-web-app":                        {"open"},
	"pack-nuget-pkg":                      {"pack"},
	"pin-certificate":                     {},
	"ping-app":                            {"ping"},
	"pkg-hotfix":                          {"hotfix", "hf"},
	"pkg-to-db":                           {"todb", "2db"},
	"pkg-to-file-system":                  {"tofs", "2fs"},
	"prune-db-templates":                  {},
	"publish-app":                         {"publishw", "publish-hub", "ph", "publish-workspace"},
	"pull-pkg":                            {"download"},
	"push-nuget-pkg":                      {"push-n", "push-nuget"},
	"push-pkg":                            {"install", "push"},
	"push-workspace":                      {"pushw"},
	"quiz":                                {},
	"read-data-binding-db":                {"get-data-binding-db"},
	"ref-to":                              {},
	"reg-web-app":                         {"reg", "cfg"},
	"regenerate-identity-signing-key":     {"identity-regenerate-key"},
	"register":                            {},
	"register-process-element":            {},
	"register-sso-provider":               {"sso-register-provider"},
	"remove-data-binding-row":             {},
	"remove-data-binding-row-db":          {},
	"remove-knowledge-source":             {},
	"remove-package-dependency":           {"remove-pkg-dependency", "remove-pkg-dep"},
	"resolve-oauth-system-user":           {},
	"restart-web-app":                     {"restart"},
	"restore-configuration":               {"restore", "rc"},
	"restore-db":                          {"rdb"},
	"restore-nuget-pkg":                   {"rn", "restore-nuget"},
	"restore-workspace":                   {"restorew", "pullw", "pull-workspace"},
	"ring":                                {},
	"run":                                 {"scenario", "run-scenario"},
	"save-state":                          {"state", "save-manifest"},
	"set-app-icon":                        {"appicon", "ai", "set-icon"},
	"set-app-version":                     {"appversion"},
	"set-background-image":                {},
	"set-dev-mode":                        {"dev", "unlock"},
	"set-entity-schema-properties":        {},
	"set-feature":                         {"feature"},
	"set-file-content-storage-connection-string": {"set-fcs-connection-string"},
	"set-fsm-config":                {"fsmc", "sfsmc"},
	"set-logo":                      {},
	"set-pkg-version":               {"spv"},
	"set-record-rights":             {},
	"set-syssetting":                {"ss", "syssetting", "sys-setting", "get-syssetting"},
	"set-user-theme":                {"apply-user-theme"},
	"set-webservice-url":            {"swu", "webservice"},
	"show-diff":                     {"diff", "compare"},
	"show-local-envs":               {"localenvs"},
	"show-package-file-content":     {"show-files", "files"},
	"start":                         {"start-server", "start-creatio", "sc"},
	"stop":                          {"stop-creatio"},
	"switch-nuget-to-dll-reference": {"nuget2dll"},
	"sync-dbhub":                    {},
	"turn-farm-mode":                {"tfm", "farm-mode"},
	"turn-fsm":                      {"tfsm", "fsm"},
	"uninstall-app-remote":          {"uninstall"},
	"uninstall-creatio":             {"uc"},
	"uninstall-identity":            {},
	"unlock-package":                {"up"},
	"unreg-web-app":                 {"unreg"},
	"unregister":                    {},
	"update-app-section":            {},
	"update-cli":                    {"update"},
	"update-client-unit-schema":     {"client-unit-schema-update"},
	"update-entity-schema":          {},
	"update-knowledge":              {},
	"update-page":                   {"page-update"},
	"update-schema":                 {"schema-update"},
	"update-sql-schema":             {"sql-schema-update"},
	"update-theme":                  {},
	"update-toolkit":                {"update-skill"},
	"upload-image":                  {},
	"upload-license":                {"license", "loadlicense", "load-license"},
	"upload-licenses":               {"lic"},
	"upsert-data-binding-row-db":    {},
	"validation-pkg":                {"validation"},
	"verify-oauth-app":              {},
	"watch-compilation":             {},
}
